Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 587, in callit
    func(*args)
  File "C:\Users\Austin and Emily\Desktop\NHL Goal Horn Scoreboard\NHLghsb.py", line 242, in checkScores
    awayTeam[whichGame] = game[0:game.find(' ')]
IndexError: list assignment index out of range
